### PR TITLE
Added grip dots to courses

### PR DESCRIPTION
**Pull request by danielleung27**

### CODE REVIEW

**Comment by danielleung27** [comment]
screenshot_1
screenshot_2

Which one looks better?

**Comment by churichard** [comment]
Try different dots (maybe from the FontAwesome library).

Also, I think that the dots should be closer to the left margin and farther away from the text.

**Comment by danielleung27** [comment]
screenshot_4
screenshot_3

**Comment by churichard** [comment]
I like the first image better, where the dots run down the width of the card. Maybe you can try making the dots a little bit smaller

**Comment by danielleung27** [comment]
screenshot_5
I also reduced the opacity

**Comment by churichard** [comment]
Grip dots have been superseded by #96

**Pull request closed without merging**
