### PR TITLE
Update ELE_2018.json

### PR DESCRIPTION
**Pull request by adeniji19**
correcting specific ele 208b requirement.

### CODE REVIEW

**Comment by bnehoran** [comment]
Could you provide a source link (as in, where this requirement is explained)?
Thanks!

**Review by bnehoran — APPROVED** [review]
I'm approving it, but I'm still wondering if you can attach a link to an official ELE source that explains the ELE requirements in regards to this course. Perhaps provide the link as a comment before you merge, so that it's in the records if we need to look back at it in the future.

**Comment by adeniji19** [comment]
http://ee.princeton.edu/sites/default/files/UG_Handbook.pdf

**Comment by churichard** [comment]
This was merged into master instead of dev. I removed it from master and added it to dev instead.

**Pull request merged**
