### PR TITLE
Make non-Romance lang courses at 105+ level count for BSE lang req

### LINKED ISSUE #365: Non-romance languages from 105+ should fulfill BSE Foreign Language dist req.
According to the [Engineering website](https://engineering.princeton.edu/undergraduate-studies/first-year-advising/degree-requirements), Romance languages from the 107-level and up count to the Foreign Language dist req. However, **non-Romance** languages from the **105**-level and up count to the Foreign Language dist req.

I don't know exactly what counts as a "Romance language." It's probably published on one of Princeton's websites somewhere, or I may just have to contact someone at Princeton to get a list of the Romance languages.

### PR DESCRIPTION
**Pull request by pranavavva**
Fixes #365

### CODE REVIEW

**Comment by bnehoran** [comment]
This looks great! Thanks for the PR @pranavavva.

Could you maybe also add the page where this is mentioned (I believe it's [this page](https://engineering.princeton.edu/undergraduate-studies/first-year-advising/degree-requirements), right?) to the `urls` field at the top of the file?

Also, if 105-level non-romance courses count, then `GER 1025` (which combines both `GER 102` and `GER 105`) probably should as well. Maybe it can just be added to the list explicitly.

**Comment by bnehoran** [comment]
Also, interestingly, it looks like ITA and POR don't even have a 105 level course.
It probably doesn't matter though.

**Comment by pranavavva** [comment]
Will do!

**Review by bnehoran — APPROVED** [review]
Looks great!

**Pull request merged**
